### ISSUE TITLE
Two kinds of users?

### ISSUE THREAD

**Issue by jeffnv** [vveleva/WaiterUp#4]
It makes sense, restaurants and whatnot can create their own pages and menus. I wouldn't expect an employer to actually create two accounts to test that. Instead of two kinds of accounts (at first), I would seed all the places information in the seeds.rb file. Focus on the client experience and seed the provider experience. At least at first.

**Comment by vveleva** [comment]
That's what I was planning to do. I thought I might as well go ahead and add a provider:boolean column to the users table from the start.
