### ISSUE TITLE
Don't use acts-as-votable

### ISSUE THREAD

**Issue by shawndromat** [vveleva/WaiterUp#5]
I think you should implement this yourself. You're a strong student and I think writing your own polymorphic voting concern would be a great backend feature that you could highlight. The Reddit on Rails class project is a good guide for this.

**Comment by shawndromat** [comment]
Oh and yeah, you should make restaurants votable too, not just menu items.

I'm also a little worried about the idea that you can't vote on something unless you ordered it. While that totally makes sense for a real website, you want to give an employer the maximum interactivity you can.

**Comment by vveleva** [comment]
I was going to make the demo account with many placed orders for demo purposes. I made that feature a bonus anyway because it might take awhile to implement.

I didn't think it was necessary to be able to rate restaurants because yelp already does that.
